package com.spring.cloud.scmproducer.web.model;

public enum ItemTypeEnum {
    FRUITS,VEGETABLES,CANNED_GOODS,MEAT,FROZEN_FOODS,DELI,SPICES,SAUCES,OILS,SNACKS,BAKERY,BEVERAGES,CEREAL,PERSONAL_CARE,HEALTH_CARE,LAUNDRY
}
